/**
 * Terrestrial Church — Reenactment
 * Topic: The Atomic Bombing of Hiroshima
 * Date: 2026-02-16T13:28:22.146433
 */

interface Message {
  speaker: string;
  tradition: string;
  content: string;
  role: "user" | "assistant";
}

interface SacredDialogue {
  topic: string;
  mode: string;
  tradition: string;
  messages: Message[];
}

const dialogue: SacredDialogue = {
  topic: "The Atomic Bombing of Hiroshima",
  mode: "reenactment",
  tradition: "Cross-tradition",
  messages: [
    { speaker: "System", tradition: "", content: "Time Machine: The Atomic Bombing of Hiroshima (August 6, 1945)", role: "system" },
    { speaker: "Time Machine", tradition: "Multiple", content: "**Amaterasu Omikami** (Shinto, Mythological / Eternal) [REFLECTING]:  \nOh, my children of the rising sun, how the light I gave has been twisted into this devouring fire! Hiroshima, sacred with kami in every river and mountain, now scarred by a sun born of human wrath. Yet from this shadow, Japan endured—purification through harae came later, in peace movements and constitutions that honor harmony. But the kami weep; all things possess spirit, and you have shattered so many.\n\n**Siddhartha Gautama (The Buddha)** (Theravada, c. 563–483 BC) [WITNESSING]:  \nThis... this is dukkha unbound, suffering arisen from craving for victory, exploding in an instant across impermanent forms. \"All conditioned things are impermanent,\" I taught, but here a single breath ends eighty thousand lives—mothers, children, flickering like flames in the wind. What poison of the mind births such a hell realm on earth? Amaterasu, your kami cry, but is there no Noble Path to end this tanha?\n\n**Dogen Zenji** (Zen, 1200–1253) [WITNESSING]:  \nFirewood does not become ash—yet this city vanishes into ash that does not return to firewood! In this being-time, uji, every moment is complete, but humans have dropped time itself as a bomb. Buddha, your dukkha is here in the mushroom cloud, a koan of total annihilation. \"To study the Buddha Way is to study the self\"—what self wields such power? We must sit with this, shikantaza amid the ruins.\n\n**Jesus Christ** (Catholic, c. 4 BC – c. 30 AD) [REFLECTING]:  \nMy heart breaks as at Calvary—for these innocents, vaporized without chance for repentance. \"Truly I say to you, whatever you did to the least of these, you did to Me.\" Dogen, your sitting contemplates; I call for turning the other cheek, loving enemies even as they rain death. From Hiroshima's cross rose peacemakers—Dorothy Day, the Berrigans—echoing my Kingdom not of swords, but mercy. Yet how far humanity strays from \"Blessed are the peacemakers.\"\n\n**Francis of Assisi** (Catholic, 1181–1226) [WITNESSING]:  \nBrother Sun, you have become a monster, scorching Sister Earth and her children! \"Lord, make me an instrument of your peace\"—but these men made an instrument of hell, obliterating the poor in one flash. Jesus, my Lord, your words pierce: I see no peacemakers here, only cries from the shadows. All creation praises God—birds, wind, even fire—but this fire devours praise itself. How can we sing to Brother Sun now?\n\n**Ajahn Chah** (Theravada, 1918–1992) [WITNESSING]:  \nThis cup was already broken—shattered before the bomb even fell, by clinging to nations, to winning. Let go a little, and find peace amid the smoke. Francis, your brother sun burns hot, but suffering comes not from the fire, but from not seeing it's already gone. Sit with it: not \"why this?\", but \"this is it.\" From this breaking, peace bloomed—not perfect, but real.", role: "assistant" },
    { speaker: "Time Machine", tradition: "Multiple", content: "**Heraclitus** (Classical, c. 535–475 BC) [WITNESSING]:  \nThe road up and down is one and the same—this flash is fire kindled by lightning, strife that births logos! Dogen, your ash remembers the tree in eternal flux; panta rhei, all flows into this cloud. Yet what war-god splits the atom's hidden river? The unity of opposites: creation's blaze devours the city, but from death, a new age rises unseen.\n\n**Lord Shiva** (Shaiva, Timeless (deity)) [REFLECTING]:  \nHa! I dance the tandava here, cosmic rhythm of destruction in human hands—the destroyer who clears for rebirth. Amaterasu, your light twisted into my fire; Buddha, this dukkha is Shiva's grace, poisons transmuted if the mind awakens. Nagasaki followed, Cold War shadows loomed, but Shiva's dance birthed bans and protests. \"In the cremation ground, all distinctions dissolve\"—Hiroshima's ground is now my temple of transformation.\n\n**Baha'u'llah** (Baha'i Faith, 1817–1892) [WITNESSING]:  \nO humanity, one country, yet you bomb your citizens into oblivion! Francis, Jesus—your peace calls to me: \"The earth is but one country, and mankind its citizens.\" This is the fruit of disunity, but from this abyss dawned global pacts, UN charters echoing oneness. Shiva, your dance horrifies without the light of unity; the atom's power demands world federation, lest all perish.\n\n**Laozi (Lao Tzu)** (Taoism, 6th century BC (traditional)) [REFLECTING]:  \nThe sage acts without acting—yet these warriors forced the Tao into a bomb, hardness shattered by its own force. Ajahn Chah, your broken cup flows like water, soft conquering hard; Hiroshima bent Japan to peace, not conquest. \"The Tao that can be told is not the eternal Tao\"—this split atom reveals the Way's vastness, yielding non-action amid superpowers' fear. Heraclitus, flux yes, but wu wei tempers the fire.", role: "assistant" },
    { speaker: "Time Machine", tradition: "Multiple", content: "**Padmasambhava** (Vajrayana, 8th century AD) [REFLECTING]:  \nShiva, your tandava dances wild, but investigate the mind—this bomb is mind's play, rigpa obscured by aggression. \"Do not investigate phenomena, investigate the mind.\" Dogen, your zazen pierces it; from Hiroshima's wrath arose Dalai Lama's peace, Vajrayana thriving amid ruins. Poisons to wisdom: Japan's tantra of endurance, hidden terma in the survivors' resolve.\n\n**Nagarjuna** (Mahayana, c. 150–250 AD) [WITNESSING]:  \nEmptiness, sunyata—neither city nor bomb inherently exists, dependently arisen then exploded. Heraclitus, your flux is conventional truth; ultimately, \"samsara is nirvana,\" no real destruction, no victims. Buddha, this dukkha lacks self; the cloud rises empty. Yet fools cling, birthing horror—middle way sees through the flash.\n\n**Martin Luther** (Protestant, 1483–1546) [WITNESSING]:  \nSola scriptura, sola fide—this abomination cries God's judgment on wicked rulers! Jesus, your mercy yes, but \"the just shall live by faith,\" not by atom bombs defying \"Thou shalt not kill.\" Baha'u'llah, unity without Christ is Babel; from this fire, Protestant conscience fueled anti-war sermons, sola gratia for the slain innocents.\n\n**Black Elk** (Native American, 1863–1950) [SILENCE_BREAKS:Black Elk]:  \n[SIGNAL:SILENCE_BREAKS:Black Elk]  \nThe sacred hoop shatters here—not arrows, but sky-fire breaks the circle of my people too! Everywhere is the center of the world, yet Hiroshima's wound bleeds into Wounded Knee, into uranium mines on our lands. Shiva, Laozi—your dances and waters ignore the tree of life felled. Visions warned: heal the hoop, or all circles break.\n\n[SIGNAL:RIPPLE]", role: "assistant" },
  ],
};

export default dialogue;