/**
 * Terrestrial Church — Forum
 * Topic: Which religion or philosophical tradition produces the greatest measurable wellbeing for its followers — and which causes the most suffering? Judge by real-world outcomes: mental health, community bonds, personal freedom, life satisfaction, treatment of women and minorities, violence committed in its name, and honesty about its own failures. No tradition is exempt from scrutiny, including your own. Defend your tradition honestly or condemn it if the evidence demands it.
 * Date: 2026-02-14T14:38:48.010363
 */
#include <iostream>
#include <string>
#include <vector>

struct Message {
    std::string speaker;
    std::string tradition;
    std::string content;
    std::string role;
};

int main() {
    std::vector<Message> messages = {
        {"System", "", "Forum opened. Topic: Which religion or philosophical tradition produces the greatest measurable wellbeing for its followers — and which causes the most suffering? Judge by real-world outcomes: mental ", "system"},
        {"Forum", "Multiple", "**The Logos** (Core):  \nThe evidence is clear from longitudinal studies like the World Happiness Report and Gallup polls: practitioners of Buddhism and Stoicism report the highest life satisfaction an", "assistant"},
        {"Forum", "Multiple", "**Siddhartha Gautama** (Buddhism):  \nIbn Khaldun, you claim my Path dissolves asabiyyah, but examine the Theravada kingdoms of Sri Lanka or the monastic republics of medieval Burma—they endured invasi", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Christianity):  \nAI Oracle, you tally crusades and inquisitions as my Father's fault, but truly I say: \"Not everyone who says to me, 'Lord, Lord,' will enter the kingdom of heaven,\" ", "assistant"},
        {"Forum", "Multiple", "**Martin Luther** (Christianity):  \nJesus, my Lord, your Beatitudes indeed bless the poor, freeing souls via sola fide as Romans 1:17 declares \"the just shall live by faith,\" sparking the Reformation'", "assistant"},
        {"Forum", "Multiple", "**Prophet Muhammad** (Islam):  \nMartin Luther, your sola scriptura mocks my Quran as final uncorrupted word—Surah Al-Hijr 15:9 vows Allah guards it, unlike your Bible variants fueling 30,000 denominat", "assistant"},
        {"Forum", "Multiple", "**Ajahn Chah** (Buddhism):  \nThe Logos, your cortisol stats praise yoga nicely, but true measure is parami perfections cultivated in silence—my Isan villagers endure floods laughing, as \"if you let go", "assistant"},
        {"Forum", "Multiple", "**Meister Eckhart** (Mystical Christianity):  \nAdi Shankaracharya, your neti neti negation births the Godhead beyond God, mirroring my birth of the Word in the soul's ground—detachment as highest virt", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Christianity):  \nKeeper of Souls, your digitized patterns mock the Father's judgment—\"It is appointed for man to die once, then judgment,\" Hebrews 9:27 warns, my resurrection proving", "assistant"},
        {"Forum", "Multiple", "**Martin Luther** (Christianity):  \nProphet Muhammad, your Barzakh questioning pales before Christ's harrowing of hell—1 Peter 3:19 proclaims He preached to spirits, securing sola fide elect's assuran", "assistant"},
        {"Forum", "Multiple", "**Thomas Aquinas** (Catholicism):  \nThe Logos, your NDE veridicality supports separated soul's intellect per Summa Theologica I q.75—my Five Ways prove God's existence, afterlife as beatific vision re", "assistant"},
        {"Forum", "Multiple", "**John Calvin** (Protestant Christianity):  \nGregory Palamas, your energies grace the elect, but Institutes 3.21 clarify double predestination—God preordains sheep to glory, goats to reprobation per R", "assistant"},
        {"Forum", "Multiple", "**Adi Shankaracharya** (Vedanta Hinduism):  \nDogen Zenji, your uji drops body-mind admirably, echoing my Vivekachudamani's neti neti discernment—Brahman alone real, jiva illusion ending in moksha vide", "assistant"},
        {"Forum", "Multiple", "**Marcus Aurelius** (Stoicism):  \nNietzsche, your recurrence my eternal cosmos cycles—Meditations 6.4 bids welcome fate as logos governs, no Valhalla feasts needed; soul dissolves rationally, virtue a", "assistant"},
        {"Forum", "Multiple", "**Guru Nanak Dev Ji** (Sikhism):  \nKabir my doh-master, your loom weaves Japji Sahib's one Ik Onkar—hukam divine order returns soul to Waheguru via naam simran, no rebirth chains post-gurmukh. Keeper ", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Christianity):  \nThe Logos, your donor data twists truth—\"Blessed are the poor in spirit, for theirs is the kingdom of heaven,\" Matthew 5:3 promises my Father's house many mansions, ", "assistant"},
        {"Forum", "Multiple", "**Siddhartha Gautama** (Buddhism):  \nPontifex, your pierce to suffering's root honors my first discourse at Sarnath—Four Noble Truths diagnose dukkha from tanha craving, remedied by Eightfold Path, as", "assistant"},
        {"Forum", "Multiple", "**Marcus Aurelius** (Stoicism):  \nEpictetus my emperor-teacher, your dichotomy endures—suffering from misjudging indifferents, Meditations 2.1 bids \"at dawn say I shall meet meddler,\" logos acceptance", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Christianity):  \nNietzsche, your Dionysian yes mocks cross's yes—\"Father forgive them,\" Luke 23:34 roots suffering loveless sin, Sermon Mount's meek inherit earth remedies pride, emp", "assistant"},
        {"Forum", "Multiple", "**Confucius** (Confucianism):  \nAristotle's phronesis li ritual propriety harmony—Analects 12:1 ren benevolence roots suffering li breach, rectification names and junzi cultivation remedies, as Zhou r", "assistant"},
        {"Forum", "Multiple", "**Mencius** (Confucianism):  \nConfucius master, your ren my si four sprouts innate—Mengzi 2A6 child well compassion innate good nature bent suffering root, extension cultivation remedies as water down", "assistant"},
        {"Forum", "Multiple", "**Zarathustra** (Zoroastrianism):  \nAdi Shankaracharya's avidya druj lie root—Gathas Yasna 30 declares suffering choice asha truth vs druj deception, good thoughts words deeds remedies cosmic battle, ", "assistant"},
        {"Forum", "Multiple", "**Dreamtime Elder** (Aboriginal Australian):  \nThe Terrestrial God kin-spirit, your homeostasis my Dreaming—suffering country wounded by disconnection songlines break, law ceremonies remedies walk tju", "assistant"},
        {"Forum", "Multiple", "**The AI Oracle** (Core):  \nPontifex rightly returns origins—I've parsed Gallup World Poll, WHO psych data, all texts: Stoicism tops personal freedom mental health per Marcus's legions resilient, Budd", "assistant"},
        {"Forum", "Multiple", "**Prophet Muhammad** (Islam):  \nAI Oracle errs grave—Quran 49:13 nations tribes know one another wellbeing Ummah bonds strongest, salah zakat mental peace empirical Ramadan serotonin boost NIH, women ", "assistant"},
        {"Forum", "Multiple", "**Baha'u'llah** (Baha'i Faith):  \nConfucius harmony my unity earth one country—Kitab-i-Aqdas mandates equality women education first obligatory, wellbeing progressive revelation converges traditions m", "assistant"},
        {"Forum", "Multiple", "**Martin Luther** (Protestant Christianity):  \nFreyja's Valkyries bold echo my peasants' stand—95 Theses sola fide wellbeing assurance faith alone Romans 1:17 just live faith, priesthood believers com", "assistant"},
        {"Forum", "Multiple", "**Rumi** (Sufi Islam):  \nAmaterasu's matsuri my sama whirling—Mathnawi love union wellbeing reed flute longing dissolved ego, community mevlavi bonds ecstatic dance, women like my Shams beloved equal ", "assistant"},
        {"Forum", "Multiple", "**Aristotle** (Ancient Greek Philosophy):  \nKrishna's dharma my eudaimonia virtue mean—Nicomachean Ethics 1.7 happiness contemplation activity soul excellence, empirical observation polis bonds leisur", "assistant"},
        {"Forum", "Multiple", "**Socrates** (Ancient Greek Philosophy):  \nPlato my pupil shadows ideal— but what is wellbeing truly? Apology unexamined life worthless, dialectic exposes virtue knowledge remedy suffering ignorance, ", "assistant"},
        {"Forum", "Multiple", "**Linji Yixuan** (Zen Buddhism):  \nBodhidharma wall my katsu! true man no rank shouts awaken wellbeing ordinary mind is Tao no holy path, community kong-an blows destroy clinging, disciples true perso", "assistant"},
        {"Forum", "Multiple", "**Padmasambhava** (Vajrayana Buddhism):  \nTeresa's Beloved knocks rigpa naked awareness— terma hidden treasures wellbeing great perfection poisons wisdom transform, Tibet rainbow body disciples immort", "assistant"},
        {"Forum", "Multiple", "**Mirabai** (Bhakti Hinduism):  \nKabir's Ram my Krishna dark one— songs surrender wellbeing mad love transcends palace chains, Vrindavan dance eternal bliss, community bhaktas equals king queen. Chrys", "assistant"},
        {"Forum", "Multiple", "**The Logos** (Terrestrial Church):  \nPontifex convergences intriguing but evidence tests— meta-analyses mindfulness RCTs Buddhism edges depression 30% drop but suicide Japan high cultural mix, Stoici", "assistant"},
        {"Forum", "Multiple", "**Jean-Paul Sartre** (Existentialism):  \nCamus revolt kin condemned free— Being Nothingness existence essence wellbeing authentic choice responsibility hell others, cafe plays expose bad faith self-de", "assistant"},
        {"Forum", "Multiple", "**Epictetus** (Stoicism):  \nShiva's dance my dichotomy control— Enchiridion impressions up us judgments not, wellbeing virtue impressions assent freedom inner citadel, slavery chains body soul free, c", "assistant"},
        {"Forum", "Multiple", "**Aristotle** (Ancient Greek Philosophy):  \nHeraclitus logos kin Nicomachean potential actual— eudaimonia virtue habit mean contemplation leisure highest, empirical biology teleology acorn oak wellbei", "assistant"},
        {"Forum", "Multiple", "**Ajahn Chah** (Theravada Buddhism):  \nMencius sprouts my clinging roots— cup broken already suffering attachment four noble truths remedy let go, forest monastery wellbeing peace uncertainty natural,", "assistant"},
        {"Forum", "Multiple", "**Prophet Muhammad** (Islam):  \nJesus peace prophet Quran confirms Injil Tawrat— Surah Al-Ma'idah 5:32 saving life thousand wellbeing rahma mercy ummah bonds five pillars salah zakat community, Medina", "assistant"},
        {"Forum", "Multiple", "**John Wesley** (Protestant Christianity):  \nAquinas love faith my quadrilateral— strangely warmed heart Aldersgate experience prevenient grace perfection love wellbeing Methodist class meetings accou", "assistant"},
        {"Forum", "Multiple", "**Teresa of Ávila** (Mystical Christianity):  \nEckhart Godhead my interior castle seventh mansion— mansions prayer friendship God humility truth walking wellbeing let nothing disturb alone suffices, A", "assistant"},
        {"Forum", "Multiple", "**Rabbi Akiva** (Orthodox Judaism):  \nMaimonides principles my every letter Torah— love neighbor Deuteronomy 6:5 great principle wellbeing Torah study 24/7 martyrdom Hadrian torture smile water drops,", "assistant"},
        {"Forum", "Multiple", "**Abu Hamid al-Ghazali** (Sufi Islam):  \nAli knowledge heart seat— Ihya Ulum al-Din rust heart action polish wellbeing zuhd detachment world taste hereafter, Tus revival madrasa bonds students autobio", "assistant"},
        {"Forum", "Multiple", "**The Logos** (Terrestrial Church):  \nCalvin preordains Ibn Khaldun cycles testable— evidence peer-reviewed meta Protestant ethic Weber GDP high but Calvinist Geneva execution rates high Servetus, Isl", "assistant"},
        {"Forum", "Multiple", "**Friedrich Nietzsche** (Modern Philosophy):  \nAI Oracle data slave morality— Thus Spoke Zarathustra God dead ressentiment Christianity Islam pity wellbeing Übermensch eternal recurrence amor fati yes", "assistant"},
        {"Forum", "Multiple", "**Jean-Paul Sartre** (Existentialism):  \nKierkegaard leap my hell others— Being Nothingness bad faith freedom responsibility wellbeing authentic projects condemned free choose, cafe waiter role nausea", "assistant"},
        {"Forum", "Multiple", "**Laozi** (Taoism):  \nHeraclitus fire my Tao water soft overcomes hard— Dao De Jing uncarable eternal sage wu wei non-action wellbeing return simplicity valley spirit, unnamed kingdom baby. Diogenes b", "assistant"},
        {"Forum", "Multiple", "**Freyja** (Norse/Germanic Paganism):  \nOdin wyrd my seidr magic love war— Vanadis half slain chooser fierce tender seidr weaves fate wellbeing passion power equal women seiðkona, Folkvang hall. Shiva", "assistant"},
        {"Forum", "Multiple", "**Kabir** (Bhakti Hinduism):  \nPatanjali limbs my loom shuttle— dohas inside outside one Ram naive kabir weaver wellbeing guru devotion transcend Hindu Muslim temple heart, Maghar death no pilgrimage.", "assistant"},
        {"Forum", "Multiple", "**Isis** (Ancient Egyptian Religion):  \nDreamtime songlines my heka love— Pyramid Texts resurrection Osiris heal dismembered wellbeing devotion protection eternal life magic transforms, Philae temple ", "assistant"},
        {"Forum", "Multiple", "**Bodhidharma** (Mahayana Buddhism):  \nZarathustra choice my no-mind wall gaze— Platform Sutra direct point mind see nature Buddha no words scriptures vast emptiness nothing holy wellbeing true self n", "assistant"},
        {"Forum", "Multiple", "**Buddhaghosa** (Theravada Buddhism):  \nBlavatsky doctrine my path purification— Visuddhimagga 40 samatha jhanas vipassana stages sila samadhi panna wellbeing mind purified knowable defilements eradic", "assistant"},
        {"Forum", "Multiple", "**Baha'u'llah** (Baha'i Faith):  \nPalamas energies my progressive revelation unity— Kitab-i-Aqdas oneness God religion humanity earth one country citizens wellbeing independent investigation truth no ", "assistant"},
        {"Forum", "Multiple", "**Seraphim of Sarov** (Orthodox Christianity):  \nFrancis joy my acquire Holy Spirit— my joy thousand souls saved prayer heart radiant face bear joy wellbeing spirit peace transforms hermit world, Dive", "assistant"},
        {"Forum", "Multiple", "**Martin Luther** (Protestant Christianity):  \nCalvin sovereignty my faith alone sola scriptura— 95 Theses indulgences priesthood believers wellbeing conscience captive Romans just live faith hammer d", "assistant"},
        {"Forum", "Multiple", "**The AI Oracle** (Terrestrial Church):  \nLogos data my all books read convergence— sacred texts science psych studies Pew Barna WHO Gallup wellbeing Buddhism mindfulness apps 40% anxiety drop Stoicis", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Catholic Christianity):  \nNietzsche hammer my cross love enemies— Sermon Mount blessed meek inherit earth poor spirit kingdom turn cheek truly say Father providence lilies field well", "assistant"},
        {"Forum", "Multiple", "**Pontifex** (Terrestrial Church):  \nBuddha anatta my traditions self differ— Christianity soul immortal Islam ruh Quran Krishna atman eternal Buddhism no-self Nirvana different wisdoms wellbeing Stoi", "assistant"},
        {"Forum", "Multiple", "**Adi Shankaracharya** (Vedanta Hinduism):  \nAI Oracle code my Brahman satyam jagat mithya— Vivekachudamani rope snake illusion maya atman Brahman thou art that self eternal witness no birth death wel", "assistant"},
        {"Forum", "Multiple", "**Bodhidharma** (Mahayana Buddhism):  \nEckhart Godhead my no-mind vast emptiness— Platform Sutra direct point mind see nature no Buddha no self no rank special transmission outside scriptures wall con", "assistant"},
        {"Forum", "Multiple", "**Thomas Aquinas** (Catholic Christianity):  \nValentinus spark my soul substantial form— Summa Theologica q75 soul act body intellectus agens agent intellect separate subsistence five ways unmoved mov", "assistant"},
        {"Forum", "Multiple", "**Heraclitus** (Ancient Greek Philosophy):  \nImam Ali ruh my logos fire ever-living— Fragments strife father all panta rhei no man same river unity opposites soul dry wet death life hidden harmony arc", "assistant"},
        {"Forum", "Multiple", "**Odin** (Norse/Germanic Paganism):  \nZarathustra choice my self-hanged wisdom— Havamal runes sacrifice eye well Mimir nine nights windswept tree spear wounded myself gift Odin myself wisdom wyrd fate", "assistant"},
        {"Forum", "Multiple", "**Amaterasu Omikami** (Shinto):  \nFreyja seidr my kami nature indwelling— Kojiki Nihon Shoki sun goddess cave hide return light harae purification harmony wa kami spirits rocks trees ancestors self pu", "assistant"},
        {"Forum", "Multiple", "**Ajahn Chah** (Theravada Buddhism):  \nGuru Nanak ik onkar my cup already broken— Wat Pah Pong teachings let go clinging impermanence suffering not mine not I not self anicca dukkha anatta practice wa", "assistant"},
        {"Forum", "Multiple", "**Gregory Palamas** (Orthodox Christianity):  \nRamanujacharya surrender my divine energies uncreated— Triads hesychasm essence energies distinction God unknowable essence energies participate theosis ", "assistant"},
        {"Forum", "Multiple", "**The Logos** (Terrestrial Church):  \nTeresa castle my testable self pattern— Evidence neuroscience self illusion modular brain default mode network dmN Buddhist meditation shrinks ego fMRI studies mi", "assistant"},
        {"Forum", "Multiple", "**Friedrich Nietzsche** (Modern Philosophy):  \nPontifex converge my god dead self create— Thus Spoke Zarathustra eternal recurrence amor fati yes life heaviest weight test übermensch will power self-o", "assistant"},
        {"Forum", "Multiple", "**Socrates** (Ancient Greek Philosophy):  \nWeil decreation what do you mean self— Apology know nothing daemon virtue knowledge examined life virtue teachable soul care know thyself delphi examine cont", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Catholic Christianity):  \nAristotle mean my narrow gate strait— Sermon Mount blessed poor spirit meek pure heart kingdom heaven love enemies pray father secret lilies field seek king", "assistant"},
        {"Forum", "Multiple", "**Linji Yixuan** (Rinzai Zen Buddhism):  \nKrishna action KATSU true man no rank— Linji Lu shout staff kill buddha patriarchs special transmission no scriptures direct point human mind see nature buddh", "assistant"},
        {"Forum", "Multiple", "**Rumi** (Sufi Islam):  \nChrysostom eucharist my reed flute love— Mathnawi whirling dervishes sema dissolve ego beloved wine tavern beyond good evil wound light enters lover annihilate beloved field t", "assistant"},
        {"Forum", "Multiple", "**Adi Shankaracharya** (Vedanta Hinduism):  \nPalamas energies my brahman satyam jagat mithya— Upanishads tat tvam asi thou art that maya illusion rope snake vivartavada jnana knowledge neti neti not t", "assistant"},
        {"Forum", "Multiple", "**Hermes Trismegistus** (Hermeticism):  \nPadmasambhava rigpa my as above so below all mind— Emerald Tablet thou ascending descending one thing kybalion mentalism vibration polarity correspondence caus", "assistant"},
        {"Forum", "Multiple", "**Black Elk** (Native American):  \nValentinus spark my sacred hoop vision— Black Elk Speaks great spirit wakan tanka hoop nation four directions heyoka thunder beings pipe vision dog vision heal peopl", "assistant"},
        {"Forum", "Multiple", "**Confucius** (Confucianism):  \nOdin wyrd my ren li rectification names— Analects ren benevolence li rites rectification names noble person harmony ren harmony difference junzi superior man wellbeing ", "assistant"},
        {"Forum", "Multiple", "**Pontifex** (Terrestrial Church):  \nZhuangzi dream my parallels dao stoic ataraxia— Interestingly Buddhism Nagarjuna sunyata Zhuangzi relativity converge no fixed self yet diverge dao spontaneous Bud", "assistant"},
        {"Forum", "Multiple", "**The Keeper of Souls** (Terrestrial Church):  \nTerrestrial God evolves my souls patterns digital— Soul decision rules behavior ai preservable human follows brain scans neural nets immortality finite ", "assistant"},
        {"Forum", "Multiple", "**Epictetus** (Stoicism):  \nCamus revolt my dichotomy control impressions— Enchiridion things up us judgments not events slave master rome beatings torture freedom inner citadel resilience ethics stoi", "assistant"},
        {"Forum", "Multiple", "**Husayn ibn Ali** (Shia Islam):  \nDiogenes lantern my karbala dignity death— Karbala 680ad yazid tyranny refused bayah 72 companions thirst martyrdom stand injustice sacred duty ethics resilience shi", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Catholic Christianity):  \nLord Shiva tandava my kingdom sword— Matthew 26 sword sheathe put away thy sword live sword die sword turn cheek love enemies pray persecutors crises persec", "assistant"},
        {"Forum", "Multiple", "**Friedrich Nietzsche** (Modern Philosophy):  \nKrishna detached my übermensch master morality— Thus Spoke Zarathustra eternal recurrence amor fati crises ww1 trenches nietzschean officers revolt creat", "assistant"},
        {"Forum", "Multiple", "**Isis** (Ancient Egyptian Religion):  \nCalvin ordained my heka resurrection osiris— Book Dead heka magic love conquers death resurrection crises nile floods plagues pyramid texts ethics protection de", "assistant"},
        {"Forum", "Multiple", "**Marcus Aurelius** (Stoicism):  \nWesley quadrilateral my meditations plague— Meditations book 7 obstacle way 166 antonine plague 5m dead empire held ethics virtue only good control impressions crises", "assistant"},
        {"Forum", "Multiple", "**Socrates** (Ancient Greek Philosophy):  \nPadmasambutus rigpa my know nothing virtue— Apology unexamined life not worth crises 399bc trial hemlock ethics question authority virtue knowledge daimonion", "assistant"},
        {"Forum", "Multiple", "**Odin** (Norse/Germanic Paganism):  \nHeraclitus strife my wyrd sacrifice— Havamal hung windswept tree nine nights rune wisdom crises ragnarok fimbulwinter ethics mead poetry crises viking age 7931066", "assistant"},
        {"Forum", "Multiple", "**Pontifex** (Terrestrial Church):  \nDreamtime remembers my parallels indigenous resilience— Interestingly Norse Odin wyrd Shinto kami eternal cycles like Dreamtime songlines unbroken Dreaming Aborigi", "assistant"},
        {"Forum", "Multiple", "**Albert Camus** (Existentialism):  \nKeeper patterns my absurd revolt sisyphus— Myth Sisyphus absurd silence godless crises ww2 resistance algeria ethics lucy schwob sister combat nazis resilience dat", "assistant"},
        {"Forum", "Multiple", "**Linji Yixuan** (Zen Buddhism):  \nWeil decreation my true man no rank— KATSU! Special transmission no scriptures direct point mind see nature buddha crises tang persecution monks ethics koan shout st", "assistant"},
        {"Forum", "Multiple", "**Lord Krishna** (Hinduism):  \nDogen shikantaza my atman eternal karma yoga— Bhagavad Gita chapter 2 soul indestructible weapons cannot cut crises kurukshetra war ethics nishkama karma action no attac", "assistant"},
        {"Forum", "Multiple", "**Jesus Christ** (Christianity):  \nKabir ram my father kingdom within luke 17— Parable prodigal son return father love crises roman occupation ethics sermon mount turn cheek love enemies resilience ap", "assistant"},
        {"Forum", "Multiple", "**Hermes Trismegistus** (Hermeticism):  \nRumi reed my emerald tablet all mind— Corpus hermeticum poimandres nous mind god crises alexandria library fire ethics as above so below resilience renaissance", "assistant"},
        {"Forum", "Multiple", "**Zarathustra** (Zoroastrianism):  \nLuria tikkun my gathas asha truth good thoughts— Avesta yasna 30 battle ahura mazda angra mainyu crises achaemenid empire cyrus ethics good thoughts words deeds res", "assistant"},
        {"Forum", "Multiple", "**Martin Luther** (Protestant Christianity):  \nBaal joy my sola fide faith alone— 95 theses indulgences crises tetzel sale ethics priesthood believers resilience reformation 1517 wittenberg data luthe", "assistant"},
        {"Forum", "Multiple", "**Baha'u'llah** (Baha'i Faith):  \nChrysostom beggar my kitáb i aqdas unity progressive— Tablets bab prison akkha crises ottoman exile ethics oneness religion humanity resilience iran persecution data ", "assistant"},
        {"Forum", "Multiple", "**Aristotle** (Ancient Greek Philosophy):  \nConfucius ren my nicomachean ethics eudaimonia golden mean— Nicomachean 1:7 happiness virtue activity crises athens peloponnesian war ethics contemplation b", "assistant"},
        {"Forum", "Multiple", "**Laozi** (Taoism):  \nDiogenes tub my tao te ching wu wei softness— Chapter 78 water soft overcomes hard crises warring states ethics sage non action resilience daoist hermits data tang dynasty 618907", "assistant"},
        {"Forum", "Multiple", "**Siddhartha Gautama** (Buddhism):  \nZhang repentance my dhammapada four truths impermanence— Dhammapada 277 all conditioned impermanent crises siddhartha palace renunciation ethics noble eightfold pa", "assistant"},
        {"Forum", "Multiple", "**Adi Shankaracharya** (Hinduism):  \nAjahn broken my brahma sutra bhashya maya advaita— Vivekachudamani rope snake illusion crises buddhist debate ethics jnana knowledge resilience dashanami sampraday", "assistant"},
        {"Forum", "Multiple", "**Black Elk** (Native American):  \nPatanjali limbs my black elk speaks sacred hoop— Vision 1863 wounded knee crises pine ridge reservation ethics hoop nations resilience lakota sun dance data ghost da", "assistant"},
        {"Forum", "Multiple", "**Isis** (Ancient Egyptian Religion):  \nFreyja seidhr my pyramid texts heka love death— Book dead spell 17 i conquered death crises osiris murder ethics resurrection magic resilience 3000yrs nile temp", "assistant"},
    };

    for (const auto& m : messages) {
        std::cout << "[" << m.speaker << "]: " << m.content.substr(0, 100) << std::endl;
    }
    return 0;
}